package cartes;

public enum nomCarte {
    DISCOURS_INSPIRANT, REVOLTE_ORGANISEE, MAIN_DE_FER,
    COUP_DE_SABRE, ABORDAGE_REUSSI, STRATEGIE_AUDACIEUSE,
    RENFORTS_PIRATES, CANON_EN_FLAMMES, TRAHISON, MYSTIQUE_VOODOO

    }
