package cartes;

public enum nomCarte {
    DISCOURS_INSPIRANT, REVOLTE_ORGANISEE, MAIN_DE_FER,
    COUP_DE_SABRE, ABORDAGE_REUSSI, STRATEGIE_AUDACIEUSE,
    RENFORTS_PIRATES, CANON_EN_FLAMMES, TRAHISON, MYSTIQUE_VOODOO,
    LEGENDE_DES_OCÉANS,EXPLOSION_DE_POUDRE,TBALLADE_PIRAE,
    ALLIANCE_DES_MARINS,EMBUSCADE_EN_MER,TOURMENT_DES_ABYSSES,FEU_DES_CANONS,

    }
